[tool.poetry]
name = "example_project"
version = "0.1.0"
description = "An example Python project."
authors = ["Harihran <thavaahariharangit@github.com>"]
packages = [
    { include = "example_project" }
]

[tool.poetry.dependencies]
structlog = "24.1.0"
python = ">=3.8"

[[tool.poetry.source]]
name = "dependabot-pip"
url = "https://jfrogghdemo.jfrog.io/artifactory/dependabot-pip"
priority = "primary"

[tool.bandit]
exclude_dirs = [".venv", "dist"]

[tool.bandit.assert_used]
skips = ['*_test.py', '*test_*.py']

[tool.mypy]
python_version = 3.11

[tool.ruff]
target-version = "py311"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
