[tool.poetry]
name = "example_project"
version = "0.1.0"
description = "An example Python project."
authors = ["Harihran <thavaahariharangit@github.com>"]
packages = [
    { include = "example_project" }
]

[tool.poetry.dependencies]
structlog = "24.1.0"
python = ">=3.8"

[[tool.poetry.source]]
name = "dependabot-pip"
url = "https://jfrogghdemo.jfrog.io/artifactory/dependabot-pip"
priority = "primary"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
